# Generated by Django 4.2.27 on 2026-01-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리 이름입니다. (예: 웹 디자인, 일러스트)', max_length=50, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0, help_text='표시 순서입니다.', verbose_name='순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='소개 페이지에 표시될 이름입니다.', max_length=100, verbose_name='이름')),
                ('bio', models.TextField(help_text='자신에 대한 소개글입니다.', verbose_name='자기소개')),
                ('email', models.EmailField(help_text='연락받을 이메일 주소입니다.', max_length=254, verbose_name='이메일')),
                ('profile_image', models.ImageField(blank=True, help_text='소개 페이지에 표시될 프로필 사진입니다.', null=True, upload_to='profile/', verbose_name='프로필 사진')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='홈페이지 상단에 크게 표시될 제목입니다.', max_length=200, verbose_name='히어로 제목')),
                ('hero_description', models.TextField(help_text='히어로 제목 아래에 표시될 설명글입니다.', verbose_name='히어로 설명')),
                ('short_intro', models.TextField(help_text='홈페이지에 표시될 짧은 소개글입니다.', verbose_name='간략 소개')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='SNS 이름입니다. (예: Instagram, Twitter, GitHub)', max_length=50, verbose_name='플랫폼')),
                ('url', models.URLField(help_text='SNS 프로필 주소입니다.', verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='표시 순서입니다. 숫자가 작을수록 먼저 표시됩니다.', verbose_name='순서')),
            ],
            options={
                'verbose_name': 'SNS 링크',
                'verbose_name_plural': 'SNS 링크',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='작업물의 제목입니다.', max_length=200, verbose_name='제목')),
                ('description', models.TextField(help_text='작업물에 대한 상세 설명입니다.', verbose_name='설명')),
                ('thumbnail', models.ImageField(help_text='작업 목록에 표시될 대표 이미지입니다.', upload_to='works/thumbnails/', verbose_name='썸네일')),
                ('external_link', models.URLField(blank=True, help_text='작업물과 관련된 외부 사이트 링크입니다. (선택사항)', null=True, verbose_name='외부 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작업물이 등록된 날짜입니다. 자동으로 설정됩니다.', verbose_name='등록일')),
                ('category', models.ForeignKey(blank=True, help_text='이 작업물의 카테고리를 선택하세요.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='portfolio.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '작업',
                'verbose_name_plural': '작업',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='작업 상세 페이지에 표시될 이미지입니다.', upload_to='works/images/', verbose_name='이미지')),
                ('order', models.PositiveIntegerField(default=0, help_text='이미지 표시 순서입니다.', verbose_name='순서')),
                ('work', models.ForeignKey(help_text='이 이미지가 속한 작업입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.work', verbose_name='작업')),
            ],
            options={
                'verbose_name': '작업 이미지',
                'verbose_name_plural': '작업 이미지',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='좋아요를 누른 시간입니다. 자동으로 설정됩니다.', verbose_name='좋아요 시간')),
                ('work', models.ForeignKey(help_text='좋아요가 눌린 작업입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='portfolio.work', verbose_name='작업')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='댓글 작성자의 닉네임입니다.', max_length=50, verbose_name='닉네임')),
                ('password', models.CharField(help_text='댓글 삭제 시 필요한 비밀번호입니다.', max_length=128, verbose_name='비밀번호')),
                ('content', models.TextField(help_text='댓글 내용입니다.', verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='댓글 작성 시간입니다. 자동으로 설정됩니다.', verbose_name='작성일')),
                ('work', models.ForeignKey(help_text='이 댓글이 달린 작업입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.work', verbose_name='작업')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['-created_at'],
            },
        ),
    ]
